name: deploy

on:
  push:
    branches:
      - main
      - dev

env:
  # dependency of the script with terraform and the other modules
  APP_NAME: "${{ github.repository }}"
  CLUSTER_NAME: "app-mt-test"
  ENVIRONMENT: "${{ github.head_ref || github.ref_name }}"
  ENV_DIR: ".iac/envs"
  # aws environment variables dependency
  AWS_REGION: "${{ secrets.AWS_REGION }}"
  AWS_ACCESS_KEY_ID: "${{ secrets.AWS_ACCESS_KEY_ID }}"
  AWS_SECRET_ACCESS_KEY: "${{ secrets.AWS_SECRET_ACCESS_KEY }"
  # spotio credentials
  SPOTIO_AUTH_USER: "${{ secrets.SPOTIO_AUTH_USER }}"
  SPOTIO_AUTH_TOKEN: "${{ secrets.SPOTIO_AUTH_TOKEN }}"
  SPOTIO_ACCOUNT: "${{ secrets.SPOTIO_ACCOUNT }}"

jobs:
  infra:
    runs-on: ubuntu-latest
    if:  "github.ref == 'refs/heads/master'"
    container:
      image: <imagem>

    steps:
      - name: Create ecs ec2 cluster
        run: ecs-manager --stage ecs-ec2-cluster

      - name: Import created ecs ec2 cluster to spotio
        run: ecs-manager --stage ecs-ec2-spotio