---
name: Create

on: workflow_dispatch

jobs:

  create:
    environment: any
    runs-on: ubuntu-latest
    container:
      image: ghcr.io.this.repo.image
      credentials:
        username: ""
        password: ""

      env:
        ENVIRONMENT: ""
        APP_NAME: ""
        CLUSTER_NAME: ""
        SPOTIO_ACCOUNT: ""
        AWS_REGION: ""
        AWS_ACCESS_KEY_ID: ""
        AWS_SECRET_ACCESS_KEY: ""
        SPOTIO_AUTH_USER: ""
        SPOTIO_AUTH_TOKEN: ""
        CONFIGS: ".iac/test"

    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Define Environment Directory
        run: |
          export ENV_DIR="$PWD/$CONFIGS"

      - name: Create Cluster
        run: ecs-manager --stage ecs-ec2-cluster
      
      - name: Create Alb
        run: ecs-manager --stage ecs-ec2-alb

      - name: Import Cluster
        run: ecs-manager --stage ecs-ec2-spotio
      
      - name: Create Service
        run: ecs-manager --stage ecs-ec2-service