---
name: Checkov
on:
  push:
    branches:
      - master
      - dev
jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      
      - name: Test Terraform
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: .
          soft_fail: true
          compact: true
          framework: terraform 